### ISSUE TITLE
clean project, adding iron:router causes crash

### ISSUE THREAD

**Issue by unaligned** [iron-meteor/iron-router#1113]
I am trying to install Iron:Router in (any) Meteor app running 1.0.1, and as soon as I run `meteor add iron:router` my app breaks with the following error:

```
auser@auser-server:~/Development/anapp$ meteor --port 58220
[[[[[ ~/Development/anapp ]]]]]

=> Started proxy.
=> Started MongoDB.
W20141209-20:50:26.327(-7)? (STDERR)
W20141209-20:50:26.408(-7)? (STDERR) /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:205
W20141209-20:50:26.409(-7)? (STDERR) }).run();
W20141209-20:50:26.409(-7)? (STDERR)    ^
W20141209-20:50:26.410(-7)? (STDERR) Error: Can't find npm module 'css-parse'. Did you forget to call 'Npm.depends' in package.js within the 'minifiers' package?
W20141209-20:50:26.410(-7)? (STDERR)     at Object.Npm.require (/home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:113:17)
W20141209-20:50:26.410(-7)? (STDERR)     at Package (packages/minifiers/minifiers.js:1)
W20141209-20:50:26.410(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:318:4
W20141209-20:50:26.411(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:329:3
W20141209-20:50:26.411(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:168:10
W20141209-20:50:26.411(-7)? (STDERR)     at Array.forEach (native)
W20141209-20:50:26.411(-7)? (STDERR)     at Function._.each._.forEach (/home/auser/.meteor/packages/meteor-tool/.1.0.36.f9z5z1++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141209-20:50:26.412(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
W20141209-20:50:32.868(-7)? (STDERR)
W20141209-20:50:32.871(-7)? (STDERR) /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:205
W20141209-20:50:32.872(-7)? (STDERR) }).run();
W20141209-20:50:32.872(-7)? (STDERR)    ^
W20141209-20:50:32.873(-7)? (STDERR) Error: Can't find npm module 'css-parse'. Did you forget to call 'Npm.depends' in package.js within the 'minifiers' package?
W20141209-20:50:32.873(-7)? (STDERR)     at Object.Npm.require (/home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:113:17)
W20141209-20:50:32.873(-7)? (STDERR)     at Package (packages/minifiers/minifiers.js:1)
W20141209-20:50:32.874(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:318:4
W20141209-20:50:32.874(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:329:3
W20141209-20:50:32.874(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:168:10
W20141209-20:50:32.874(-7)? (STDERR)     at Array.forEach (native)
W20141209-20:50:32.874(-7)? (STDERR)     at Function._.each._.forEach (/home/auser/.meteor/packages/meteor-tool/.1.0.36.f9z5z1++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141209-20:50:32.875(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
W20141209-20:50:37.714(-7)? (STDERR)
W20141209-20:50:37.718(-7)? (STDERR) /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:205
W20141209-20:50:37.718(-7)? (STDERR) }).run();
W20141209-20:50:37.719(-7)? (STDERR)    ^
W20141209-20:50:37.720(-7)? (STDERR) Error: Can't find npm module 'css-parse'. Did you forget to call 'Npm.depends' in package.js within the 'minifiers' package?
W20141209-20:50:37.720(-7)? (STDERR)     at Object.Npm.require (/home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:113:17)
W20141209-20:50:37.720(-7)? (STDERR)     at Package (packages/minifiers/minifiers.js:1)
W20141209-20:50:37.720(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:318:4
W20141209-20:50:37.721(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/packages/minifiers.js:329:3
W20141209-20:50:37.721(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:168:10
W20141209-20:50:37.721(-7)? (STDERR)     at Array.forEach (native)
W20141209-20:50:37.721(-7)? (STDERR)     at Function._.each._.forEach (/home/auser/.meteor/packages/meteor-tool/.1.0.36.f9z5z1++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141209-20:50:37.722(-7)? (STDERR)     at /home/auser/Development/anapp/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

This particular output was from a completely clean app, just after `meteor create anapp`

**Edit:**
Apparently this happens when I run any app, although I first noticed it just after I added I:R to another project. Something must have gotten screwed up in my environment.

**Edit 2:**
Removed/re-installed meteor, re-added I:R. No problem. Closing.

**Comment by gregorwilson** [comment]
Same happened for me with `Error: Can't find npm module body-parse'` - reinstalled meteor as above and that fixed it.
