### ISSUE TITLE
Posting malformed JSON throws an error

### ISSUE THREAD

**Issue by pierre-b** [iron-meteor/iron-router#1167]
Hi, Im building a server-side API and when I POST a malformed JSON payload the router crashes:

```
W20150108-12:32:58.096(0)? (STDERR) SyntaxError: Unexpected token m
W20150108-12:32:58.097(0)? (STDERR)     at Object.parse (native)
W20150108-12:32:58.098(0)? (STDERR)     at parse (/home/vagrant/.meteor/packages/iron_router/.1.0.6.cm6b0v++os+web.browser+web.cordova/npm/node_modules/body-parser/lib/types/json.js:68:17)
W20150108-12:32:58.098(0)? (STDERR)     at /home/vagrant/.meteor/packages/iron_router/.1.0.6.cm6b0v++os+web.browser+web.cordova/npm/node_modules/body-parser/lib/read.js:91:18
W20150108-12:32:58.099(0)? (STDERR)     at IncomingMessage.onEnd (/home/vagrant/.meteor/packages/iron_router/.1.0.6.cm6b0v++os+web.browser+web.cordova/npm/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
W20150108-12:32:58.100(0)? (STDERR)     at IncomingMessage.g (events.js:180:16)
W20150108-12:32:58.100(0)? (STDERR)     at IncomingMessage.emit (events.js:92:17)
W20150108-12:32:58.101(0)? (STDERR)     at _stream_readable.js:943:16
W20150108-12:32:58.101(0)? (STDERR)     at process._tickDomainCallback (node.js:463:13)
```

Did I miss something in the configuration ?

The route is under /server/router.js :

``` javascript
Router.map(function() {
  this.route('/v1/send', { where: 'server' }).post(function() {

  });
}); 
```

Thanks

**Comment by pierre-b** [comment]
This a critical issue, because you can't release an API to the world if it crashes your app everytime the received request is not perfect... don't you think @cmather ?

**Comment by cmather** [comment]
Agreed it's annoying. Check the underlying connect body parser library. Maybe we can replace it with something custom.

**Comment by pierre-b** [comment]
Is it something you can fix in the next Iron router release please ?

Like having an onError callback in the route:
```javascript
Router.map(function() {
  this.route('/v1/send', { where: 'server' }).post(function() {

  })
  .onError(function(error, req, res){
  // handle middleware error
  });
}); 
```

**Comment by Oyabi** [comment]
Same problem here.
Have you find a solution ?

**Comment by pierre-b** [comment]
Not yet, to me it's a critical bug in iron router which is supposed to catch this error !

@cmather could you please tell us if you planned to try/catch middlewares errors ?

**Comment by pierre-b** [comment]
@Oyabi here is a hack, it deactivates the bodyparser and make it yourself.

```javascript
// DISABLE JSON BODY PARSER

Router.configureBodyParsers = function () {
  // Router.onBeforeAction(Iron.Router.bodyParser.json());
  Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({extended: false}));
};

Router.route('/api/endpoint', { where: 'server' }).post(function () {

  var body;

  // parse JSON yourself on every API routes
  
  try {
    body = JSON.parse(this.request.body);
  }
  catch(e){
    response.writeHead(400, {"Content-Type": "application/json"});
    return response.end(JSON.stringify({error: 'invalid JSON'}));
  }
});
```

**Comment by Oyabi** [comment]
Than you very much. 
I will test your solution.

**Comment by Type1J** [comment]
It seems that body-parsers needs to try/catch some places, which is outside of iron:router.

I don't know if It matters how it's handled, but a solution such as the one by @pierre-b will have to be used in production apps until then. Here's my variant of @pierre-b's version:

    Router.configureBodyParsers = function() {
      var textBodyParser = Iron.Router.bodyParser.text({type: 'json'});
      var checkedJsonBodyParser = function(req, res, next) {
        textBodyParser(req, res, function() {
          try {
            req.body = JSON.parse(req.body);
            next();
          } catch (e) {
            req.bodyParseError = "invalid JSON";
            next();
          }
        });
      };

      Router.onBeforeAction(checkedJsonBodyParser);
      Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({extended:false}));
    };

Having middleware that places an a "bodyParseError" field on the request that's usually undefined unless there's an error seems like a reasonable solution to me because it handles the parsing in the middleware, as expected, instead of requiring the route to handle it explicitly. However, the route still needs to handle the error condition.

    Router.route('/api/1.0/input', {
      where: 'server',
      action: function() {
        if (this.request.bodyParseError) {
          this.response.writeHead(400, {"Content-Type": "application/json"});
          this.response.end(JSON.stringify({
            status: "ERROR",
            message: this.request.bodyParseError
          }));
          return;
        }

        // Do actual handling here . . .
        ...
    }

Again, this is not really better than @pierre-b's way in an app, but I think it might behave in a more predictable way than @pierre-b way if it were to be included in iron:router's own Router.configureBodyParsers.

I think the ultimate solution might involve passing "invalid JSON" to the next() function as a few other errors seem to be handled that way, but I'm not sure how to detect those in the route.

See https://github.com/expressjs/body-parser/blob/master/lib/types/json.js

@cmather 2 Questions:
 1. How would you detect an error passed to next() in a Router.route() action function?
 2. Could something like the above be included in iron:router until body-parser fixes their error handling?

**Comment by jancurn** [comment]
There's even a simpler way. You can intercept errors from the JSON body parser as follows:

``` javascript
Router.configureBodyParsers = function () {
    Router.onBeforeAction(function(req, res, next) {
        var myNext = function(err) {
            if( err ) {
                console.log("ERROR OCCURRED: ", err);
                // TODO: handle the error any way you want
                return next(err);
            }
            return next();
        };
        return Iron.Router.bodyParser.json()(req, res, myNext);
    });
   Router.onBeforeAction(Iron.Router.bodyParser.urlencoded({extended: false})); 
};
```

**Comment by ant45de** [comment]
If anyone is looking for an option to inspect the raw body, you can find it in err.body!
