### ISSUE TITLE
files organized in my Meteor Public Folder are not being displayed

### ISSUE THREAD

**Issue by emmanuelkalengailunnga** [iron-meteor/iron-router#1259]
Can I do this within my Meteor Public Folder? :
src="/images/fnc/east/men/basketball/u5/p/teams/farmington.png"
For some reasons, it's not working. Thank you for your assistance.
Sincerely,
Cyrano Skram

**Comment by ofthewood** [comment]
the same for me . Need absolute URL.

**Comment by emmanuelkalengailunnga** [comment]
Before, my files were only 3 folders deep, and they were displayed, but now that they are about 8 folders deep, they don't show up anymore: is this a platform's strategic restriction? Thanks.

**Comment by emmanuelkalengailunnga** [comment]
Directory: /home/emma/Desktop
Tue Mar  3 11:35:07 MST 2015
emma@paircent:~/Desktop> cd ../krslx
emma@paircent:~/krslx> meteor
[[[[[ ~/krslx ]]]]]                           

=> Started proxy.                             
=> Started MongoDB.                           
                                              
/home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: spawn ENOMEM
    at errnoException (child_process.js:1001:11)
    at ChildProcess.spawn (child_process.js:948:11)
    at Object.exports.spawn (child_process.js:736:9)
    at [object Object]._.extend._spawn (/home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:224:31)
    at [object Object]._.extend.start (/home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:81:22)
    at [object Object]._.extend._runOnce (/home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:653:16)
    at [object Object]._.extend._fiber (/home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:771:28)
    at /home/emma/.meteor/packages/meteor-tool/.1.0.41.1e51u4e++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/tools/run-app.js:366:12
emma@paircent:~/krslx>

**Comment by emmanuelkalengailunnga** [comment]
I am getting the exception above, while building the app. Can anyone help me get passed it? Greatly appreciate it, thank you.

**Comment by channikhabra** [comment]
I can't even go 3 level deep. Files in `/public/report/file-name` are accessible, but files in `/public/report/weekly/file-name`  gives a not-found error from iron-router.

**Comment by bipin244** [comment]
src="../images/fnc/east/men/basketball/u5/p/teams/farmington.png"
try this

**Comment by chrisbutler** [comment]
i don't think this is an iron-router issue
