### ISSUE TITLE
Meteor.userId error on server side route

### ISSUE THREAD

**Issue by dcsan** [iron-meteor/iron-router#1326]
I have a very simple server side route, but for some reason this error below is called when parsing those routes.
This just started happening today, although it doesn't seem to be related to an I:R update.

```
Meteor.startup ->

  if Meteor.isServer
    console.log("create server routes")
    Router.map ->
      @route "reloadAll",
        where: "server"
        path: "/server"
        action: ->
          console.log("route / reloadAll")
```

throws this - the actual route action is never reached.

```
Error: Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
    at Object.Meteor.userId (packages/accounts-base/accounts_server.js:19:1)
    at [object Object].Meteor.startup.Router.map.route.where (both/appRoutes.coffee:7:3)
    at packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at [object Object].dispatch (packages/iron:middleware-stack/lib/middleware_stack.js:275:1)
    at [object Object].RouteController._runRoute (packages/iron:router/lib/route_controller_server.js:63:1)
```

**Comment by dcsan** [comment]
found the problem. some other global route configs.
