### ISSUE TITLE
Server-side routes don't work with Spiderable

### ISSUE THREAD

**Issue by olivierpascal** [iron-meteor/iron-router#1352]
```
$ meteor create test
test$ meteor add iron:router
test$ meteor add spiderable
```

```
Router.route('/test', {
  name: 'test',
  where: 'server',
  action: function() {
    this.response.end();
  }
});
```

Then access `http://localhost:3000/test?_escaped_fragment_=`

Error:

```
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
  at Object.Meteor._nodeCodeMustBeInFiber (/me/.meteor/local/build/programs/server/packages/meteor.js:942:11)
  at [object Object]._.extend.get (/me/.meteor/local/build/programs/server/packages/meteor.js:954:12)
  at [object Object].RouteController.lookupOption (/me/.meteor/local/build/programs/server/packages/iron_router.js:139:29)
  at new Controller.extend.constructor (/me/.meteor/local/build/programs/server/packages/iron_router.js:99:21)
  at [object Object].ctor (/me/.meteor/local/build/programs/server/packages/iron_core.js:142:17)
  at Function.Route.createController (/me/.meteor/local/build/programs/server/packages/iron_router.js:504:18)
  at Function.Router.createController (/me/.meteor/local/build/programs/server/packages/iron_router.js:794:24)
  at Function.Router.dispatch (/me/.meteor/local/build/programs/server/packages/iron_router.js:1322:25)
  at Object.router (/me/.meteor/local/build/programs/server/packages/iron_router.js:611:12)
  at next (/me/.meteor/packages/webapp/.1.2.0.t8smg4++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
  at /me/.meteor/local/build/programs/server/packages/ongoworks_spiderable.js:171:11
  at ChildProcess.exithandler (child_process.js:662:7)
  at ChildProcess.emit (events.js:98:17)
  at maybeClose (child_process.js:766:16)
  at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

You may ask why use spiderable with a server-side route? Well, I use this route to generate a Facebook Open Graph Object (with fb:app_id, og:title, etc.) and when Facebook fetch the page, I think that Spiderable try to phantomize it.

**Comment by olivierpascal** [comment]
Ok, I've found a solution. In order to spiderable work, I stub Meteor in the static page version, by adding the following in <head></head>.

```
<script type="text/javascript">
  Meteor     = {status: function() {return {connected: true}}};
  Deps       = {flush: function() {}};
  Tracker    = {flush: function() {}};
  DDP        = {_allSubscriptionsReady: function() {return true}};

  spiderable = {Spiderable: {_initialSubscriptionsStarted: true}};
  Package = {
    spiderable: spiderable,
    'ongoworks:spiderable': spiderable // and any spiderable forks you may use
  };
</script>
```

I hope it will help other people.
