### ISSUE TITLE
Issue with "spiderable" and phantomjs

### ISSUE THREAD

**Issue by mikkhait** [iron-meteor/iron-router#1375]
After latest update of the packages my "spiderable" functionality broke. Can some one please confirm that there is an issue with Iron.Router and "spiderable"?

```
I20150626-00:25:55.741(-7)? spiderable: phantomjs failed: Error: Command failed:
I20150626-00:25:55.741(-7)?     at ChildProcess.exithandler (child_process.js:658:15)
I20150626-00:25:55.741(-7)?     at ChildProcess.emit (events.js:98:17)
I20150626-00:25:55.741(-7)?     at maybeClose (child_process.js:766:16)

I20150626-00:25:55.741(-7)?     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
I20150626-00:25:55.741(-7)? stderr:

W20150626-00:25:55.773(-7)? (STDERR) Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.

W20150626-00:25:55.773(-7)? (STDERR)     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
W20150626-00:25:55.773(-7)? (STDERR)     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)

W20150626-00:25:55.773(-7)? (STDERR)     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)

W20150626-00:25:55.773(-7)? (STDERR)     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)

W20150626-00:25:55.773(-7)? (STDERR)     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)

W20150626-00:25:55.773(-7)? (STDERR)     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)

W20150626-00:25:55.773(-7)? (STDERR)     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)

W20150626-00:25:55.774(-7)? (STDERR)     at Object.router (packages/iron:router/lib/router.js:15:1)

W20150626-00:25:55.774(-7)? (STDERR)     at next (/Users/aaa/.meteor/packages/webapp/.1.2.0.15p5axz++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)

W20150626-00:25:55.774(-7)? (STDERR)     at packages/spiderable/spiderable_server.js:123:1
```

**Comment by mikkhait** [comment]
Closing because of this #1192
