### ISSUE TITLE
Spiderable still not working

### ISSUE THREAD

**Issue by dnish** [iron-meteor/iron-router#1423]
Hey guys,
just created a new clean meteor project and tried to run it with "Spiderable" (because I've problems with it on my main project). Without any packages, everything runs fine, I get a clean response with <code>?_escaped_fragment=1</code>

My next step was to add "iron-router" to my project, after doing this, I've tested it again and now get the following error:

<code>
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (C:\Users\Dennis\AppData\Local\.meteor\packages\webapp\1.2.0\npm\node_modules\connect\lib\proto.js:190:15)
    at packages/spiderable/spiderable_server.js:123:1
</code>

Tested on a Windows 10 and Ubuntu 14.04 machine, same error.

Installed packages:

<code>
meteor-platform
autopublish
insecure
spiderable
iron:router
</code>

I've also tested it on the meteor.com servers, there I get also an "Internal Server Error".

**Comment by dr-dimitru** [comment]
try [this spiderable fork](https://github.com/jazeee/jazeee-meteor-spiderable) we fixed most of the issues, it works like a charm

**Comment by chrisbutler** [comment]
@dr-dimitru :+1:
