### ISSUE TITLE
i got no method error when use the new version today

### ISSUE THREAD

**Issue by floodpeak** [iron-meteor/iron-router#1453]
@chrisbutler 
TypeError: Object [object Object] has no method '_setLookupHost'
    at [object Object].Controller (packages/iron_controller/lib/controller.js:25:1)
    at new Controller.extend.constructor (packages/iron_router/lib/route_controller.js:14:1)
    at [object Object].ctor (packages/iron_core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron_router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron_router/lib/router_server.js:39:1)
    at Object.router (packages/iron_router/lib/router.js:15:1)
    at next (/Users/zhouhongfeng/.meteor/packages/webapp/.1.2.2.1gnjjz2++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/Users/zhouhongfeng/.meteor/packages/webapp/.1.2.2.1gnjjz2++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
    at Object.fn [as handle] (/Users/zhouhongfeng/.meteor/packages/webapp/.1.2.2.1gnjjz2++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:74:14)
    at next (/Users/zhouhongfeng/.meteor/packages/webapp/.1.2.2.1gnjjz2++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)

**Comment by bogdanrn** [comment]
Related #1452

**Comment by chrisbutler** [comment]
closing as duplicate
