### ISSUE TITLE
Tripple slash `///` causing exception

### ISSUE THREAD

**Issue by dr-dimitru** [iron-meteor/iron-router#1462]
I've found strange exception when in URL is three slashes used (found my mistake :).
This issue doesn't appear with two or more than three slashes.
[Example](https://iron-router-progress.meteor.com///wait) - in console:
```shell
Exception in callback of async function: TypeError: Cannot read property 'getName' of undefined
    at h.lookupTemplate (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:87:5319)
    at h.render (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:87:5585)
    at h.action (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:87:5183)
    at o (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:62:867)
    at p (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:62:3912)
    at null.next (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:3:6647)
    at null.<anonymous> (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:89:3243)
    at https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:87:11379
    at t.extend.withValue (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:3:6389)
    at u (https://iron-router-progress.meteor.com/5c03e3f161439fa021977292d82c530592f205ad.js:87:11333)
```

**Comment by sveinburne** [comment]
You will notice on [the official `url` specifications](https://tools.ietf.org/html/rfc3986#section-3.3) that a path, i.e. the section of the url after the authoritative portion (`iron-router-progress.meteor.com/[path]`), has to start with a non-empty segment, namely `segment-nz    = 1*pchar`. So your path was not compliant with those specifications. Perhaps the router shall explicitly states the route is not url compliant?

**Comment by dr-dimitru** [comment]
[google 4-time slash](https://www.google.ru////search?newwindow=1&hl=en&authuser=0&biw=1379&bih=815&site=imghp&tbm=isch&sa=1&q=meteorjs&oq=meteorjs&gs_l=img.3..0j0i10l4j0i10i24l5.1512.1602.0.1775.2.2.0.0.0.0.69.129.2.2.0....0...1c.1.64.img..0.2.129.9mr5JXlhCzI#imgrc=S6Qf4I7IAA3bgM%3A)
[google triple slash](https://www.google.ru///search?newwindow=1&hl=en&authuser=0&biw=1379&bih=815&site=imghp&tbm=isch&sa=1&q=meteorjs&oq=meteorjs&gs_l=img.3..0j0i10l4j0i10i24l5.1512.1602.0.1775.2.2.0.0.0.0.69.129.2.2.0....0...1c.1.64.img..0.2.129.9mr5JXlhCzI#imgrc=S6Qf4I7IAA3bgM%3A)
[google double slash](https://www.google.ru//search?newwindow=1&hl=en&authuser=0&biw=1379&bih=815&site=imghp&tbm=isch&sa=1&q=meteorjs&oq=meteorjs&gs_l=img.3..0j0i10l4j0i10i24l5.1512.1602.0.1775.2.2.0.0.0.0.69.129.2.2.0....0...1c.1.64.img..0.2.129.9mr5JXlhCzI#imgrc=S6Qf4I7IAA3bgM%3A)

As you see Google works in favour of best user experience, and we all should too.

**Comment by sveinburne** [comment]
Ahah good point! Well I'm not involved in the project, it's their call.
