### ISSUE TITLE
1.0.0-pre1 and Kadira

### ISSUE THREAD

**Issue by picsoung** [iron-meteor/iron-router#833]
Just upgrade from Meteor 0.8.3 to 0.9.2.1 and iron-router 1.0.0-pre1

When I launch my app I got this conflict:

``` bash
/Users/picsoung/Documents/Dev/3scale/apisearch/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:2579
 throw err;
  ^
 Error: A route for the path 'function (params, options) {                                      // 145
   return this.handler.resolve(params, options);                                          // 146
 }' already exists.
    at Function.Router.route (packages/iron:router/lib/router.js:125)
     at Function.response (app/server/apiRouter.js:97:8)
     at Function.Router.map (packages/iron:router/lib/router.js:91)
     at app/server/apiRouter.js:5:8
    at app/server/apiRouter.js:228:3
    at /Users/picsoung/Documents/Dev/3scale/apisearch/.meteor/local/build/programs/server/boot.js:161:10
    at Array.forEach (native)
     at Function._.each._.forEach (/Users/picsoung/.meteor/packages/meteor-tool/.1.0.30.1c9wz7r++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
     at /Users/picsoung/Documents/Dev/3scale/apisearch/.meteor/local/build/programs/server/boot.js:82:5
```

Don't really know what's happening and how to solve this.

**Comment by mickeyren** [comment]
@cmather this is still broken on the latest.
